---
driver:
  name: ec2
  instance_type: t2.large
  region: us-west-2
  iam_profile_name: S3WorkerRoleforEC2
  tags:
    Name: test-kitchen-<%= ENV['USER'] %>
    Owner: <%= ENV['USER'] %>
provisioner:
  name: chef_zero
  log_level: info
  require_chef_omnibus: 14.4
  always_update_cookbooks: true

platforms:
  - name: amazon
    driver:
      image_id: ami-6cd6f714
    transport:
      username: ec2-user
  - name: ubuntu-18.04LTS
    driver:
      image_id: ami-0bbe6b35405ecebdb
    transport:
      username: ubuntu
  - name: windows-2012

suites:
  - name: metrics_maker
    run_list:
      - recipe[metric_maker]
      - recipe[metric_maker::examples]
    attributes: {}
